name: quick_shelter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  http: ^0.12.1
  shared_preferences: ^0.5.7
  camera: ^0.5.8+2
  path_provider: ^1.6.10
  path: ^1.6.4
  image_picker: ^0.6.7+1
  mime: ^0.9.6+3
  #intl: ^0.16.1
  transparent_image: ^1.0.0
  flutter_money_formatter: ^0.8.3
  material_design_icons_flutter: ^4.0.5345
  fluttertoast: ^7.0.1
  webview_flutter: ^0.3.22+1
  open_file: ^3.0.1
  pdf: ^1.9.0
  flutter_share: ^1.0.2+1
  flutter_launcher_icons: ^0.7.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/welcome.png
    - assets/images/welcome_x2.png
    - assets/images/welcome_x3.png
    - assets/images/welcome1.png
    - assets/images/welcome1x2.png
    - assets/images/welcome1x3.png
    - assets/images/prop.png
    - assets/images/person.png
    - assets/images/building.png
    - assets/images/1_big.png
    - assets/images/1_thumbnail.png
    - assets/images/2_big.png
    - assets/images/2_thumbnail.png
    - assets/images/3_big.png
    - assets/images/3_thumbnail.png
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/logoBlack.png
    - assets/images/logoBlack1.png
    - assets/images/logoBlack2.png
    - assets/icons/bath.svg
    - assets/icons/bed.svg
    - assets/icons/home.svg

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product-Sans
      fonts:
        - asset: assets/fonts/Product-Sans-400.ttf
        - asset: assets/fonts/Product-Sans-Bold-700.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
